language: python

sudo: false
cache: pip

install:
  - pip install -r requirements.txt

script:
  # Use Sphinx to make the html docs
  - sphinx-build . -a _build/html
  # Tell GitHub not to use jekyll to compile the docs
  - touch _build/html/.nojekyll

deploy:
    - provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: _build/html
      on:
        branch: master